#%RAML 1.0

title: A title
description: A description
version: 1.0
baseUri: http://example.com/{version}

schemas:
  user: !include ../../schemas/user.json

/:home:
  get:
    queryParameters:
      userName: string
  /:user:
    get:
      body:
        application/json:
          schema: user
      responses:
        200:
          body:
            application/json:
              schema: user
