#%RAML 1.0
title: 这里是标题
description: 这里是描述
mediaType: application/json

schemas:
  user: !include ../schemas/user.json

traits:
  paged:
    queryParameters:
      start:
        type: number

resourceTypes:
  collection:
    get:
      is: paged



/home:
  get:
    queryParameters: 
      type: number
    body:
      application/json:
        schema: user
    responses: 
      200:
        body: 
          application/json:
            schema: user
      201:
        body: 
          application/json:
            schema: user
  /user:
    get:
      description: 获取所有用户信息
      body:
        application/json:
          schema: user
    /:uid:
      get:
        body:
          application/json:
            schema: user
      delete:
        body:
          application/json:
            schema: user
